# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15SdT7Yaah4S2sVRuNo8sxWTZDZ6yEdz3
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tipe_payments = pd.read_csv('Hasil_Join_Payments.csv')
tipe_payments

#Handling Missing Values
tipe_payments.isna().sum()

#Handling Duplicate
table_payments_duplicate = tipe_payments.duplicated(subset=['order_id'], keep='last')
table_payments_clean_dup = tipe_payments[~table_payments_duplicate]
table_payments_clean_dup

# Count occurrences of each payment type
payment_counts = table_payments_clean_dup['payment_type'].value_counts()

# Create a DataFrame with counts
df_counts = pd.DataFrame({'Payment Type': payment_counts.index, 'Count': payment_counts.values})

# Use boxplot with flierprops to customize outlier appearance
sns.boxplot(x='Count', data=df_counts, fliersize=8, flierprops=dict(markerfacecolor='red', marker='D'))

# Add labels and title
plt.xlabel('Count', fontsize=8)
plt.ylabel('Payment Type', fontsize=8)
plt.title('Payment Type Outliers', fontsize=8)

# Show the plot
plt.show()